CREATE TABLE [dbo].[CLIENTS] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [Code]           VARCHAR (250)    NOT NULL,
    [RegisterDate]   DATETIME         NOT NULL,
    [Name]           VARCHAR (250)    NULL,
    [Surname]        VARCHAR (250)    NULL,
    [BirthDate]      DATETIME         NULL,
    [Dni]            VARCHAR (50)     NULL,
    [Address]        VARCHAR (250)    NULL,
    [Location]       VARCHAR (250)    NULL,
    [PostalCode]     VARCHAR (10)     NULL,
    [Province]       VARCHAR (250)    NULL,
    [Phone]          VARCHAR (50)     NULL,
    [Email]          VARCHAR (250)    NULL,
    [Resp1Name]      VARCHAR (250)    NULL,
    [Resp1Surname]   VARCHAR (250)    NULL,
    [Resp1Dni]       VARCHAR (50)     NULL,
    [Resp1Phone]     VARCHAR (50)     NULL,
    [Resp1Email]     VARCHAR (250)    NULL,
    [Payment]        VARCHAR (250)    NULL,
    [BankName]       VARCHAR (250)    NULL,
    [SwitfBIC]       VARCHAR (250)    NULL,
    [Iban]           VARCHAR (250)    NULL,
    [CardNumber]     VARCHAR (250)    NULL,
    [ExpirationDate] VARCHAR (5)      NULL,
    [Cvc]            VARCHAR (3)      NULL,
    [State]          VARCHAR (250)    NULL,
    [Notes]          VARCHAR (500)    NULL,
    [Resp2Name]      VARCHAR (250)    NULL,
    [Resp2Surname]   VARCHAR (250)    NULL,
    [Resp2Dni]       VARCHAR (50)     NULL,
    [Resp2Phone]     VARCHAR (250)    NULL,
    [Resp2Email]     VARCHAR (250)    NULL,
    [ReportNotes]    VARCHAR (500)    NULL,
    CONSTRAINT [PK_CLIENTS] PRIMARY KEY CLUSTERED ([Id] ASC)
);

