CREATE TABLE [dbo].[FEES] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [ProductId] UNIQUEIDENTIFIER NOT NULL,
    [Price]     FLOAT (53)       NOT NULL,
    [StartDate] DATETIME         NOT NULL,
    [EndDate]   DATETIME         NOT NULL,
    [AudUsu]    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_FEES] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PRODUCTS] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[PRODUCTS] ([Id]),
    CONSTRAINT [FK_USERS] FOREIGN KEY ([AudUsu]) REFERENCES [dbo].[USERS] ([Id])
);

