CREATE TABLE [dbo].[FREE_DAYS] (
    [Id]        UNIQUEIDENTIFIER NOT NULL,
    [Season]    NVARCHAR (50)    NULL,
    [ClientId]  UNIQUEIDENTIFIER NOT NULL,
    [Date]      DATETIME         NOT NULL,
    [ProductId] UNIQUEIDENTIFIER NULL,
    [Type]      NVARCHAR (10)    NULL,
    CONSTRAINT [PK_FREE_DAYS] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CLIENTS_FREE_DAYS] FOREIGN KEY ([ClientId]) REFERENCES [dbo].[CLIENTS] ([Id]),
    CONSTRAINT [FK_CLIENTS_PRODUCTS] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[PRODUCTS] ([Id])
);

